---
#______________________________________
# Install dependencies

- name: '[EL] Install packages'
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - lsof
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: '[Ubuntu] Install packages'
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - lsof
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

#______________________________________
# Detect init system
# Supported: supervisord, init

- name: Check if Galaxy is managed by supervisor
  supervisorctl: name="galaxy:" state=present
  register: supervisor_galaxy
  ignore_errors: yes

- name: Set init-type to supervisord
  set_fact:
    init_type: 'supervisord'
  when: supervisor_galaxy.failed is undefined

- name: Check if Galaxy is managed by systemd/upstart
  service: name="galaxy" state=started
  register: systemd_galaxy
  ignore_errors: yes
  when: supervisor_galaxy.failed is defined

- name: Set init-type to systemd
  set_fact:
    init_type: 'init'
  when:
    - supervisor_galaxy.failed is defined
    - systemd_galaxy.failed is undefined

#______________________________________
# Install galaxyctl scripts

- name: '[EL] Set supervisord conf path'
  set_fact:
    supervisord_conf_path: '/etc'
  when:
    - ansible_os_family == "RedHat"
    - init_type == "supervisord"

- name: '[Ubuntu] Set supervisord conf path'
  set_fact:
    supervisord_conf_path: '/etc/supervisor'
  when:
   - ansible_os_family == "Debian"
   - init_type == "supervisord"

- name: 'Clone Galaxy Central Management Tool (galaxyctl)'
  git:
    repo: 'https://github.com/mtangaro/galaxyctl.git'
    clone: yes
    dest: '{{ galaxy_FS_path }}/galaxyctl'

- set_fact:
    pip_exe: '/bin/pip'
  when: ansible_os_family == "RedHat"

- set_fact:
    pip_exe: '/usr/bin/pip'
  when: ansible_os_family == "Debian"

- name: Install galaxyctl
  pip:
    name: . # install local package
    chdir: '/home/galaxy/galaxyctl'
    executable: '{{ pip_exe }}'
  become_user: root
  become_method: sudo
  when: galaxyctl_is_installed.rc != 0

- name: Edit galaxyctl ini file
  ini_file:
    dest: '/etc/galaxyctl/galaxyctl.ini'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: 'galaxy', option: 'init_system', value: '{{ init_type }}' }          
    - { section: 'galaxy', option: 'supervisord_conf_file', value: '{{ supervisord_conf_path }}/supervisord.conf' }
    - { section: 'galaxy', option: 'galaxy_config_file', value: '{{ galaxy_config_file }}' }      
    - { section: 'galaxy', option: 'uwsgi_pid_file', value: '{{ galaxy_log_path }}/uwsgi.pid' }
    - { section: 'galaxy', option: 'galaxyctl_log_file', value: '{{ galaxy_log_path }}/galaxyctl.log' }
  become_user: root
  become_method: sudo
