---
- name: Mount Onedata reference data space
  include: onedata.yml
  when: refdata_provider_type == 'onedata'

- name: Download reference data
  include: refdata-download.yml
  when: refdata_provider_type == 'download'

- name: '[Onedata/Downlod] Let Galaxy be aware of reference data'
  include: locs.yml
  when: (refdata_provider_type == 'onedata') or (refdata_provider_type == 'download')

- name: '[CVMFS] Let Galaxy be aware of reference data'
  include: cvmfs_locs.yml
  when: (refdata_provider_type == 'cvmfs') or (refdata_provider_type == 'cvmfs_preconfigured')

# Send success mail only if this is the last play, i.e. no tools and no reference data installation.
- include: send_success_mail.yml
 
# Lock the role to avoid user custom settings rewrite during updates.
- name: Lock role
  template:
    src: 'indigo-dc.galaxycloud-refdata.lock.j2'
    dest: '{{lock_file_path}}/indigo-dc.galaxycloud-refdata.lock'
  become_user: root
  become_method: sudo
