---
  include: onedata.yml
  when: refdata_provider_type == 'onedata'

- name: Download Reference Data
  include: refdata-download.yml
  when: refdata_provider_type == 'download'

- name: Let Galaxy be aware of reference data
  include: locs.yml
