---
# Run the role only if galaxy is installed.
- stat: path='{{ galaxy_install_path }}/run.sh'
  register: galaxy_installed

# Run the role only if the infrastructure is not locked for this role.
- stat: path='{{lock_file_path}}/indigo-dc.galaxycloud-refdata.lock'
  register: refdata_role_locked

- include: prerequisites.yml
  when:
   - galaxy_installed.stat.exists
   - not refdata_role_locked.stat.exists

- name: Install and Configure Reference Data
  include: install.yml
  when:
    - galaxy_installed.stat.exists 
    - not refdata_role_locked.stat.exists
    - get_refdata
  become_user: "{{ galaxy_user }}"
  become: true

# Lock the role only if this is the last play,
- meta: flush_handlers

#________________________________
# Lock the role to avoid user custom settings rewrite during updates.
- name: Lock role
  template:
    src: 'indigo-dc.galaxycloud-refdata.lock.j2'
    dest: '{{lock_file_path}}/indigo-dc.galaxycloud-refdata.lock'
  become_user: root
  become_method: sudo
