---
# Add a fast check to speed reconfiguration
- stat: path='{{ galaxy_install_path }}/run.sh'
  register: galaxy_installed

- include: prerequisites.yml
  when: galaxy_installed.stat.exists

- include: check_galaxy.yml
  when: galaxy_installed.stat.exists

- name: Install and Configure Reference Data
  include: install.yml
  when: galaxy_installed.stat.exists and get_refdata
  become_user: "{{ galaxy_user }}"
  become: true
