---
# Add a fast check to speed reconfiguration
- stat: path=/usr/local/bin/galaxy-startup
  register: galaxy_installed

- name: Wait Galaxy is up
  include: check-galaxy-instance.yml
  when: galaxy_installed.stat.exists

- name: Install and Configure Reference Data
  include: install.yml
  when: galaxy_installed.stat.exists and get_refdata
