---
- name: Copy onedatactl.py script
  template:
    src: 'onedatactl.py.j2'
    dest: '/usr/local/bin/onedatactl'
    mode: 'a+x'
  become_user: root
  become_method: sudo

- name: Copy onedatactl.ini file
  template:
    src: 'onedatactl.ini.j2'
    dest: '{{ onedatactl_config_file }}'
  become_user: root
  become_method: sudo

- name: Configure onedatactl configuration file
  ini_file:
    dest: '{{ onedatactl_config_file }}'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: 'refdata', option: 'mountpoint', value: '{{ refdata_dir }}' }
    - { section: 'refdata', option: 'provider', value: '{{ refdata_provider }}' }
    - { section: 'refdata', option: 'token', value: '{{ refdata_token }}' }
  become_user: root
  become_method: sudo

- name: Mount Onedata  Reference Data space
  shell: 'onedatactl --mount --refdata'
