---
# This recipe is currently run only on VMs

#________________________________
# Check if galaxy is up
# If yes, a mail is sent to the user, otherwise the role will fail.

- name: Check if Galaxy is online
  uri:
    url: '{{ galaxy_instance_url }}'
  register: result
  until: (result.status == 200) or (result.status == 302)
  retries: 30
  delay: 10

#________________________________
# Send mail using preconfigured script from indigo-dc.galaxycloud-os

- name: 'Copy success mail to avoid "does not exist, or is not readable" error'
  copy:
    src: '{{ custom_utils_path }}/mail_wrapper.yaml'
    dest: '/tmp/mail_wrapper.yaml'
    remote_src: yes

- name: Send success mail to alert user. ONLY FOR TESTING, this is not passing gmail antispam filters
  include: '/tmp/mail_wrapper.yaml'
