---
# This recipe is currently run only on VMs

#________________________________
# Check if galaxy is up
# If yes, a mail is sent to the user, otherwise the role will fail.

- name: Check if Galaxy is online
  uri:
    url: '{{ galaxy_instance_url }}'
  register: result
  until: (result.status == 200) or (result.status == 302)
  retries: 30
  delay: 10

#________________________________
# Send mail using ansible

- name: Download vars anda mail template
  get_url:
    url: '{{ item.url }}'
    dest: '{{ item.dest }}'
  with_items:
    - { url: 'https://raw.githubusercontent.com/indigo-dc/ansible-role-galaxycloud/master/vars/mail_vars.yml', dest: '/tmp/mail_vars.yml' }
    - { url: 'https://raw.githubusercontent.com/indigo-dc/ansible-role-galaxycloud/master/templates/mail_success.html.j2', dest: '/tmp/mail_success.html.j2' }

- include_vars: /tmp/mail_vars.yml

- name: Copy mail
  template:
    src: '/tmp/mail_success.html.j2'
    dest: '/tmp/mail_success.txt'

- name: Send mail to alert user. ONLY FOR TESTING, this is not passing gmail antispam filters
  mail:
    from: '{{ mail_from }}'
    to: "{{ GALAXY_ADMIN_EMAIL }}"
    subject: '{{ mail_subject }}'
    body: '{{ lookup("file", "/tmp/mail_success.txt") }}'
    subtype: html
    #attach: /tmp/instructions.pdf
