---
- name: Restart Galaxy
  command: "/usr/local/bin/galaxyctl restart galaxy --force"
  ignore_errors: yes
  become_user: root
  become_method: sudo

- name: Check if Galaxy is on line
  uri:
    url: '{{ galaxy_instance_url }}'
  register: result
  until: result.status == 200
  retries: 30
  delay: 10
