---
- name: Set galaxy restart command
  set_fact:
    galaxy_restart: "{{ galaxy_custom_script_path }}/galaxyctl restart galaxy --force"

#______________________________________
# Docker restart galaxy only if running.

- name: '[Docker] check if galaxy is running'
  stat: '/var/log/galaxy/uwsgi.pid'
  register: galaxy_pid 
  when: ansible_virtualization_type == "docker"

- name: '[Docker] Restart Galaxy'
  command: '{{ galaxy_restart }}'
  ignore_errors: yes
  become_user: root
  become_method: sudo
  when:
    - galaxy_pid.stat.exists
    - ansible_virtualization_type == "docker"

#______________________________________
# VM (always restart galaxy, to ensure it is running).

- name: '[VM] Restart Galaxy'
  command: '{{ galaxy_restart }}'
  ignore_errors: yes
  become_user: root
  become_method: sudo
  when: ansible_virtualization_type != "docker"

- name: '[VM] Check if Galaxy is on line'
  uri:
    url: '{{ galaxy_instance_url }}'
  register: result
  until: result.status == 200
  retries: 30
  delay: 10
  when: ansible_virtualization_type != "docker"
