---
- name: Restart Galaxy
  command: "galaxy-restart"
  ignore_errors: yes
  become_user: root
  become_method: sudo

- name: Wait Galaxy is up
  include: check-galaxy-instance.yml
  #static: no # This is a temporary workaround for https://github.com/ansible/ansible/issues/18178 
