---
- name: Restart Galaxy
  command: "{{ galaxy_custom_script_path }}/galaxyctl restart galaxy --force"
  ignore_errors: yes
  become_user: root
  become_method: sudo

- name: Check if Galaxy is on line
  uri:
    url: '{{ galaxy_instance_url }}'
  register: result
  until: result.status == 200
  retries: 30
  delay: 10
  when: ansible_virtualization_type != "docker"
