---
# handlers file for ansible-role-galaxycloud-refdata

- name: restart galaxy
  include: handlers/galaxy_restart.yml
  static: no # This is a temporary workaround for https://github.com/ansible/ansible/issues/18178
